/* SAGE demo prototype — all data is synthetic and for demonstration only. */
const savedTheme = (() => { try { return localStorage.getItem('sage-theme'); } catch { return null; } })();
const state = { role: 'student', page: 'dashboard', theme: savedTheme === 'dark' ? 'dark' : 'light', selectedCategory: 'Campus environment', rating: 0, timer: null, seconds: 25 * 60 };

const roleInfo = {
  admin: { label: 'Administrator', name: 'Dr. Meera Shah', initials: 'MS', nav: [['dashboard', '⌂', 'Dashboard'], ['students', '♧', 'Students'], ['analytics', '◔', 'Risk Analytics'], ['interventions', '◫', 'Interventions'], ['insights', '✦', 'Insights'], ['feedback', '▣', 'Student Feedback'], ['reports', '▤', 'Reports'], ['settings', '⚙', 'Settings']] },
  faculty: { label: 'Faculty / Mentor', name: 'Prof. Kiran Rao', initials: 'KR', nav: [['dashboard', '⌂', 'Dashboard'], ['students', '♧', 'My Students'], ['interventions', '◫', 'Interventions'], ['progress', '◔', 'Student Progress'], ['insights', '✦', 'Feedback Insights'], ['reports', '▤', 'Reports']] },
  student: { label: 'Student', name: 'Aarav Sharma', initials: 'AS', nav: [['dashboard', '⌂', 'My Dashboard'], ['attendance', '◷', 'My Attendance'], ['performance', '◔', 'My Performance'], ['helper', '✦', 'AI Study Helper'], ['plan', '☷', 'Study Plan'], ['goals', '◎', 'Goals'], ['achievements', '♛', 'Achievements'], ['interventions', '◫', 'My Interventions'], ['feedback', '▣', 'Student Feedback'], ['notifications', '◉', 'Notifications'], ['profile', '◌', 'Profile']] }
};

const app = document.querySelector('#app');
const chart = (variant = 'admin') => `<div class="line-chart" aria-label="${variant === 'student' ? 'Performance has improved from 61 to 72 percent across six assessments.' : 'Support-priority trend has decreased from 86 to 64 students across six months.'}">
  <div class="labels-y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div>
  <svg class="chart-svg" viewBox="0 0 600 165" preserveAspectRatio="none" role="img">
    <defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#70cbbb" stop-opacity=".32"/><stop offset="1" stop-color="#70cbbb" stop-opacity="0"/></linearGradient></defs>
    <path class="area" d="M0,${variant === 'student' ? '118 L100,105 L200,117 L300,83 L400,66 L500,55 L600,42 L600,165 L0,165 Z' : '25 L100,39 L200,60 L300,74 L400,82 L500,95 L600,107 L600,165 L0,165 Z'}" />
    <path class="line" d="M0,${variant === 'student' ? '118 L100,105 L200,117 L300,83 L400,66 L500,55 L600,42' : '25 L100,39 L200,60 L300,74 L400,82 L500,95 L600,107'}" />
    <path class="secondary-line" d="M0,${variant === 'student' ? '98 L100,100 L200,91 L300,87 L400,75 L500,67 L600,60' : '43 L100,46 L200,54 L300,60 L400,67 L500,70 L600,77'}" />
  </svg>
  <div class="labels-x"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div>
</div>`;

function attendanceHeatmap() {
  const months = [
    { name: 'May', days: 31, absent: [4, 9, 14, 19, 27], neutral: [11] },
    { name: 'Jun', days: 30, absent: [5, 10, 16, 22, 27], neutral: [17, 30] },
    { name: 'Jul', days: 31, absent: [3, 8, 13, 18, 24, 29], neutral: [15] },
    { name: 'Aug', days: 31, absent: [4, 9, 14, 19, 23, 27, 30], neutral: [12, 26] }
  ];
  let presentCount = 0;
  let absentCount = 0;
  let neutralCount = 0;
  const rows = months.map(month => {
    const absentDays = new Set(month.absent);
    const neutralDays = new Set(month.neutral);
    const cells = Array.from({ length: month.days }, (_, index) => {
      const day = index + 1;
      const status = neutralDays.has(day) ? 'no-class' : absentDays.has(day) ? 'absent' : 'present';
      const label = status === 'no-class' ? 'Holiday or no class scheduled' : status === 'absent' ? 'Absent' : 'Present';
      if (status === 'present') presentCount += 1;
      if (status === 'absent') absentCount += 1;
      if (status === 'no-class') neutralCount += 1;
      return `<span class="attendance-cell ${status}" role="img" aria-label="${month.name} ${day}: ${label}" title="${month.name} ${day}: ${label}"></span>`;
    }).join('');
    return `<div class="attendance-month-row"><span class="attendance-month-name">${month.name}</span><div class="attendance-grid monthly-attendance-grid" style="--days:${month.days}">${cells}</div></div>`;
  }).join('');
  const scheduledCount = presentCount + absentCount;
  const attendanceRate = Math.round((presentCount / scheduledCount) * 100);
  return `<section class="card attendance-heatmap-card" aria-labelledby="attendance-consistency-title">
    <div class="card-heading attendance-heatmap-heading"><div><h2 id="attendance-consistency-title">Attendance consistency</h2><p>Your daily attendance across the current and previous three demo months.</p></div><span class="pill green">4-month view</span></div>
    <div class="heatmap-summary"><div><strong>${presentCount}</strong><span>days present</span></div><div class="summary-divider"></div><div class="attendance-absence"><strong>${absentCount}</strong><span>days absent</span></div><div class="summary-divider"></div><div class="attendance-neutral"><strong>${neutralCount}</strong><span>holidays / no class</span></div><div class="attendance-streak"><span>Attendance rate</span><strong>${attendanceRate}%</strong></div></div>
    <div class="attendance-heatmap" aria-label="Attendance activity grid for May through August 2026 showing ${presentCount} present days, ${absentCount} absent days, and ${neutralCount} holidays or unscheduled days."><div class="heatmap-track"><div class="attendance-month-list">${rows}</div></div></div>
    <div class="attendance-legend"><span><i class="legend-cell present"></i>Present · ${presentCount} days</span><span><i class="legend-cell absent"></i>Absent · ${absentCount} days</span><span><i class="legend-cell no-class"></i>Holiday / no class · ${neutralCount} days</span><span class="legend-note">Each square represents one calendar day.</span></div>
  </section>`;
}

function showWelcome() {
  document.title = 'SAGE | Student Analytics, Guidance & Empowerment';
  app.innerHTML = `<section class="welcome-page">
    <div class="welcome-copy">
      <div class="brand"><span class="brand-mark">S</span> SAGE</div>
      <div class="welcome-head">
        <span class="eyebrow">Student success platform</span>
        <h1>Spot signals early.<br><span>Help students thrive.</span></h1>
        <p>SAGE brings student analytics, human guidance, and empowering learning support together—so every student can move forward with confidence.</p>
      </div>
      <div class="promise"><span>Early signals</span><span>Human-reviewed support</span><span>Better outcomes</span></div>
    </div>
    <div class="sign-panel"><div class="sign-card">
      <button class="theme-toggle welcome-theme-toggle" data-action="theme" aria-label="Switch to ${state.theme === 'light' ? 'dark' : 'light'} theme">${state.theme === 'light' ? '☾' : '☀'} <span>${state.theme === 'light' ? 'Dark mode' : 'Light mode'}</span></button>
      <div class="brand" style="color:#17223b"><span class="brand-mark">S</span> SAGE</div>
      <h2 style="margin-top:34px">Welcome back</h2><p>Choose your experience to explore the SAGE prototype.</p>
      <div class="role-choices" role="group" aria-label="Select demo role">
        ${[['admin', '⌘', 'Admin'], ['faculty', '♧', 'Faculty'], ['student', '◎', 'Student']].map(([key, icon, label]) => `<button class="role-choice ${key === state.role ? 'selected' : ''}" data-role="${key}" type="button"><span class="role-icon">${icon}</span>${label}</button>`).join('')}
      </div>
      <label class="field">Email / Student ID<input type="text" placeholder="Enter your email or ID" value="${state.role === 'student' ? 'STU-2026-0147' : ''}" /></label>
      <label class="field">Password<input type="password" placeholder="Enter your password" value="demo123" /></label>
      <button class="primary wide" id="signin" type="button">Explore ${roleInfo[state.role].label} Demo →</button>
      <p class="demo-note">Prototype access only. <button id="try-demo" type="button">Use demo credentials</button></p>
    </div></div>
  </section>`;
  app.querySelectorAll('[data-role]').forEach(btn => btn.addEventListener('click', () => { state.role = btn.dataset.role; state.page = 'dashboard'; showWelcome(); }));
  app.querySelector('#signin').addEventListener('click', shell);
  app.querySelector('#try-demo').addEventListener('click', () => { toast('Demo credentials added. You can now enter the prototype.'); });
  app.querySelectorAll('[data-action]').forEach(btn => btn.addEventListener('click', actionHandler));
}
function pageName() {
  return roleInfo[state.role].nav.find(item => item[0] === state.page)?.[2] || 'Dashboard';
}
function shell() {
  const info = roleInfo[state.role];
  const nav = info.nav.map(([page, icon, label]) => `<button class="nav-link ${state.page === page ? 'active' : ''}" data-page="${page}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');
  app.innerHTML = `<div class="shell">
    <aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">S</span>SAGE</div><div class="side-caption">${info.label} space</div><nav class="nav-list" aria-label="Main navigation">${nav}</nav>
      <div class="support-card"><strong>Need support?</strong><p>Connect with a mentor, counselor, or academic support team.</p><button data-action="help">Get help</button></div>
      <div class="user-side"><span class="avatar ${state.role === 'student' ? 'mint' : ''}">${info.initials}</span><span><strong>${info.name}</strong><small>${info.label}</small></span></div>
      <button class="logout-button" data-action="logout"><span>↗</span> Log out</button>
    </aside>
    <section class="workarea"><header class="topbar"><button class="icon-button mobile-menu" id="menu" aria-label="Toggle navigation">☰</button><span class="breadcrumb">SAGE <span> / </span> <strong>${pageName()}</strong></span><span class="topbar-spacer"></span><label class="header-search">⌕<input aria-label="Search" placeholder="Search SAGE" /></label><div class="header-actions"><button class="theme-toggle" data-action="theme" aria-label="Switch to ${state.theme === 'light' ? 'dark' : 'light'} theme">${state.theme === 'light' ? '☾' : '☀'} <span>${state.theme === 'light' ? 'Dark' : 'Light'}</span></button><button class="icon-button" data-action="notifications" aria-label="Notifications">♢</button><button class="icon-button" data-action="logout" aria-label="Sign out">↗</button></div></header><main id="page-content"></main></section>
  </div>`;
  app.querySelectorAll('[data-page]').forEach(btn => btn.addEventListener('click', () => {
    state.page = btn.dataset.page;
    updateSidebarActive();
    renderPage();
  }));
  app.querySelector('#menu')?.addEventListener('click', () => app.querySelector('#sidebar').classList.toggle('open'));
  app.querySelectorAll('[data-action]').forEach(btn => btn.addEventListener('click', actionHandler));
  renderPage();
}

function updateSidebarActive() {
  app.querySelectorAll('.nav-link[data-page]').forEach(btn => {
    const isActive = btn.dataset.page === state.page;
    btn.classList.toggle('active', isActive);
    btn.setAttribute('aria-current', isActive ? 'page' : 'false');
  });
}
function header(title, text, notice = true) { return `<div class="page-heading"><div><h1>${title}</h1><p>${text}</p></div>${notice ? '<div class="notice">◉ <span><b>Demo environment</b> · Synthetic data only</span></div>' : ''}</div>`; }
function stat(label, value, meta, tint = '#ddf5ee', cls = '') { return `<article class="stat-card" style="--tint:${tint}"><div class="label">${label}</div><div class="value">${value}</div><div class="meta ${cls}">${meta}</div></article>`; }
function statusPill(value) { const map = { 'High': 'rose', 'Medium': 'amber', 'Low': 'green', 'Improving': 'green', 'Action planned': 'blue', 'Under review': 'amber', 'Resolved': 'green' }; return `<span class="pill ${map[value] || 'slate'}">${value}</span>`; }

function adminDashboard() {
  return `<div class="page">${header('Student Support Overview', 'See early signals, coordinate timely support, and monitor progress.')}
  <section class="stat-grid">${stat('Total students', '1,248', 'Across 6 programmes', '#e8efff', 'gray')}${stat('Students needing attention', '64', '↓ 12% from last month', '#ffe9ed')}${stat('Active interventions', '38', '29 human-reviewed', '#fff2d9', '')}${stat('Students improving', '71%', '↑ 8% this term', '#ddf5ee', '')}</section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Support-priority trend</h2><p>Students receiving an early-support review over time</p></div><button class="link-button" data-page="analytics">View analytics →</button></div>${chart()}<div class="chart-legend"><span>Students needing support</span><span>Active interventions</span></div></article><article class="card"><div class="card-heading"><div><h2>Support priority</h2><p>Current distribution</p></div></div><div class="donut-layout"><div class="donut"><div><strong>1,248</strong><small>students</small></div></div><ul class="legend-list"><li><span><i style="--dot:#bd4b62"></i>Higher priority</span><strong>14</strong></li><li><span><i style="--dot:#b76c00"></i>Medium priority</span><strong>50</strong></li><li><span><i style="--dot:#7bc9bc"></i>On track</span><strong>1,184</strong></li></ul></div></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Students to review</h2><p>Human review is required before any support action.</p></div><button class="link-button" data-page="students">View all →</button></div>${studentTable()}</article><article class="card"><div class="card-heading"><div><h2>What changed recently?</h2><p>Signals behind new support reviews</p></div></div><div class="signal-list"><div class="signal"><span class="signal-icon" style="--tint:#fff0f1;--colour:#bd4b62">◷</span><span class="signal-name">Attendance changes<small>18 students this week</small></span><b class="signal-val">↓ 14%</b></div><div class="signal"><span class="signal-icon" style="--tint:#eaf2ff;--colour:#3e69d6">◔</span><span class="signal-name">Academic performance<small>12 students this week</small></span><b class="signal-val">↓ 9%</b></div><div class="signal"><span class="signal-icon" style="--tint:#fff4df;--colour:#b76c00">⌁</span><span class="signal-name">Learning activity<small>9 students this week</small></span><b class="signal-val">↓ 21%</b></div></div><div class="insight-callout" style="margin-top:18px"><strong>Potential institutional support barrier</strong><p>Recurring Wi-Fi feedback and reduced learning activity are an observed association in this demo dataset. Local investigation is required.</p></div></article></section>
</div>`;
}

function studentTable() { return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Student</th><th>Attendance</th><th>Performance</th><th>Support priority</th><th>Recommended action</th></tr></thead><tbody><tr><td><span class="student-name"><span class="avatar mint">AS</span>Aarav Sharma</span></td><td>58%</td><td>46%</td><td>${statusPill('High')}</td><td><button class="row-action" data-action="student-detail">Review profile</button></td></tr><tr><td><span class="student-name"><span class="avatar">PN</span>Priya Nair</span></td><td>67%</td><td>61%</td><td>${statusPill('Medium')}</td><td><button class="row-action" data-action="intervention">Assign support</button></td></tr><tr><td><span class="student-name"><span class="avatar mint">RK</span>Rohan Kumar</span></td><td>72%</td><td>63%</td><td>${statusPill('Medium')}</td><td><button class="row-action" data-action="student-detail">Review profile</button></td></tr></tbody></table></div>`; }

function feedbackDashboard() {
  return `<div class="page">${header('Student Feedback', 'Turn anonymous student feedback into actionable institutional insights.')}
  <section class="stat-grid">${stat('Total feedback', '248', 'This semester', '#e8efff', 'gray')}${stat('Average rating', '3.4 / 5', 'Across all categories', '#fff2d9', 'gray')}${stat('Needs attention', '17', '3 increasing this week', '#ffe9ed')}${stat('Resolved issues', '42', '↑ 9 this term', '#ddf5ee')}</section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Student experience trend</h2><p>Average rating across the current semester</p></div><span class="pill blue">Semester</span></div>${chart('student')}<div class="chart-legend"><span>Average experience rating</span><span>Semester target</span></div></article><article class="card"><div class="card-heading"><div><h2>Ratings by category</h2><p>From anonymous and identified feedback</p></div></div><div class="signal-list"><div class="signal"><span class="signal-icon">⌁</span><span class="signal-name">Internet / Wi-Fi<small>43 feedback mentions</small></span><b class="signal-val">2.1 ★</b></div><div class="signal"><span class="signal-icon" style="--tint:#fff3e0;--colour:#b76c00">▤</span><span class="signal-name">Classroom infrastructure<small>28 feedback mentions</small></span><b class="signal-val">2.4 ★</b></div><div class="signal"><span class="signal-icon" style="--tint:#e4f5ef;--colour:#187564">▥</span><span class="signal-name">Library resources<small>18 feedback mentions</small></span><b style="color:#187564">4.1 ★</b></div></div></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Common student issues</h2><p>Priority considers frequency, rating, and trend.</p></div><button class="link-button" data-action="issue-modal">Issue details →</button></div><div class="issue-list"><div class="issue"><span class="issue-num">01</span><div><h3>Wi-Fi connectivity</h3><p>43 mentions · average rating 2.1 ★ · trend increasing</p></div><div class="issue-meta"><b>HIGH</b><small>Under review</small></div></div><div class="issue"><span class="issue-num">02</span><div><h3>Classroom fans</h3><p>28 mentions · average rating 2.4 ★ · trend stable</p></div><div class="issue-meta"><b style="color:#b76c00">MEDIUM</b><small>Action planned</small></div></div><div class="issue"><span class="issue-num">03</span><div><h3>Canteen pricing</h3><p>21 mentions · average rating 2.6 ★ · trend stable</p></div><div class="issue-meta"><b style="color:#b76c00">MEDIUM</b><small>Under review</small></div></div></div></article><article class="card"><div class="card-heading"><div><h2>Institutional insight</h2><p>Demo / simulated insight</p></div></div><div class="insight-callout"><strong>Potential learning-environment barrier detected</strong><p>Students reporting Wi-Fi issues in this demo data also show lower average learning activity. This is an observed association—not a proven cause—and warrants institutional review.</p></div><div class="explanation" style="margin-top:15px">SAGE keeps individual support needs distinct from institutional feedback. Student identities are not shown in aggregate insights unless feedback was explicitly non-anonymous.</div></article></section>
</div>`;
}

function facultyDashboard() {
  return `<div class="page">${header('My Students', 'Prioritise human-reviewed support for the students assigned to you.')}
  <section class="stat-grid">${stat('Assigned students', '42', 'B.Tech · Semester 3', '#e8efff', 'gray')}${stat('Need attention', '7', '2 new this week', '#ffe9ed')}${stat('Active interventions', '5', '2 check-ins this week', '#fff2d9', 'gray')}${stat('Students improving', '9', 'Following a support plan', '#ddf5ee')}</section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Priority list</h2><p>Review signals and recommendations before assigning support.</p></div><button class="link-button" data-action="student-detail">Open Aarav's profile →</button></div>${studentTable()}</article><article class="card"><div class="card-heading"><div><h2>Upcoming follow-ups</h2><p>Stay connected at the right moment</p></div></div><div class="plan-item"><span class="plan-check">1</span><span><strong>Aarav Sharma</strong><span>Academic mentoring · Today, 3:30 PM</span></span><span class="plan-duration">Today</span></div><div class="plan-item"><span class="plan-check">2</span><span><strong>Priya Nair</strong><span>Attendance check-in · Tomorrow, 11:00 AM</span></span><span class="plan-duration">Tomorrow</span></div><div class="plan-item"><span class="plan-check">3</span><span><strong>Rohan Kumar</strong><span>Review intervention outcome</span></span><span class="plan-duration">Fri</span></div><button class="secondary wide" data-action="intervention">Schedule follow-up</button></article></section>
  <section class="content-grid equal"><article class="card"><div class="card-heading"><div><h2>Feedback insight</h2><p>Aggregate student feedback relevant to your cohort</p></div></div><div class="insight-callout"><strong>Wi-Fi feedback increased among first-year students</strong><p>22 anonymous mentions this month. This may warrant a local infrastructure review.</p></div></article><article class="card"><div class="card-heading"><div><h2>Responsible support</h2><p>How SAGE supports decisions</p></div></div><div class="explanation">SAGE generates support hypotheses from available signals. It never makes automatic decisions about students; human review remains essential.</div></article></section>
</div>`;
}

function profileDetail() {
  return `<div class="page">${header('Student Support Profile', 'Aarav Sharma · STU-2026-0147 · B.Tech Computer Science · Semester 3')}
  <section class="detail-grid" style="margin-bottom:20px"><article class="card profile-card"><span class="avatar mint">AS</span><span><h2>Aarav Sharma</h2><p>Academic mentor: Prof. Kiran Rao · Last updated today</p></span><span style="margin-left:auto">${statusPill('High')}</span></article><article class="card"><span class="pill blue">Human review required</span><p style="margin:10px 0 0;color:#627087;font-size:12px">Support priority is a probabilistic early-warning signal, not a label or decision.</p></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Why now?</h2><p>Three significant changes in the last four weeks</p></div><span class="pill slate">Demo / simulated</span></div><div class="why-now"><div class="change"><strong>Attendance</strong><span>82% → 58%</span><small>↓ 24 percentage points</small></div><div class="change"><strong>Mathematics</strong><span>71% → 46%</span><small>↓ 25 percentage points</small></div><div class="change"><strong>Learning activity</strong><span>14 → 6 sessions</span><small>↓ 57% this month</small></div></div><div class="explanation" style="margin-top:16px">These combined changes triggered an early-support review. They do not establish the reason for the changes.</div></article><article class="barrier-card"><div class="barrier-top"><span class="barrier-emblem">◌</span><div><h3>Primary support barrier</h3><p>AI-generated support hypothesis</p></div></div><h3 style="margin:14px 0 0">Academic learning difficulty</h3><p>Confidence: High · Based on available simulated signals</p><ul><li>Mathematics trend declined below target</li><li>Practice activity reduced recently</li><li>Check-in response indicates topic difficulty</li></ul><button class="primary" data-action="intervention">Review recommendation</button></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Recommended support plan</h2><p>Faculty may accept, adapt, or decline this suggestion.</p></div></div><div class="plan-item"><span class="plan-check">✓</span><span><strong>Academic mentoring</strong><span>Weekly 20-minute check-in with subject mentor</span></span><span class="plan-duration">4 weeks</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Mathematics practice set</strong><span>Ten guided questions after each revision</span></span><span class="plan-duration">Weekly</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Revision session</strong><span>Join Tuesday's topic refresher</span></span><span class="plan-duration">Tue</span></div></article><article class="card"><div class="card-heading"><div><h2>Follow-up</h2><p>Next review: Friday, 22 August</p></div></div><button class="primary wide" data-action="intervention">Assign support plan</button><button class="secondary wide" style="margin-top:10px" data-action="note">Add faculty note</button></article></section>
</div>`;
}

function studentDashboard() {
  return `<div class="page">${header('My Dashboard', 'Your personal space for making steady progress.', false)}
  <section class="student-hero"><div class="hero-content"><span class="eyebrow">Thursday, 14 August</span><h1>Good morning, Aarav 👋</h1><p>Every focused step counts. Let’s make today a little stronger.</p><button class="primary" data-page="helper">See today’s study plan →</button></div></section>
  <section class="metric-row" style="margin-bottom:22px"><article class="metric"><span class="metric-label">Attendance</span><div class="metric-value">78%</div><div class="mini-progress"><i style="--progress:78%"></i></div></article><article class="metric"><span class="metric-label">Academic performance</span><div class="metric-value">72%</div><div class="mini-progress"><i style="--progress:72%;--progress-color:#496ed3"></i></div></article><article class="metric"><span class="metric-label">Study consistency</span><div class="metric-value">84%</div><div class="mini-progress"><i style="--progress:84%;--progress-color:#8e67d4"></i></div></article><article class="metric"><span class="metric-label">Learning streak</span><div class="metric-value">7 days 🔥</div><div class="mini-progress"><i style="--progress:70%;--progress-color:#e6a025"></i></div></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Today’s personalised focus</h2><p>Based on your available learning and progress data</p></div><span class="pill green">Adaptive plan</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Mathematics: algebra revision</strong><span>Your focus area—start with core concepts.</span></span><span class="plan-duration">45 min</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Programming practice</strong><span>Keep the positive routine going.</span></span><span class="plan-duration">30 min</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Review practice mistakes</strong><span>Use your last quiz to guide revision.</span></span><span class="plan-duration">15 min</span></div><button class="primary wide" data-action="focus">Start a focus session</button></article><article class="card"><div class="card-heading"><div><h2>Learning streak</h2><p>Small, regular effort makes a difference.</p></div><strong style="color:#e38d11">7 days 🔥</strong></div><div class="streak"><div class="day done"><b>✓</b>Mon</div><div class="day done"><b>✓</b>Tue</div><div class="day done"><b>✓</b>Wed</div><div class="day today"><b>14</b>Thu</div><div class="day"><b>15</b>Fri</div><div class="day"><b>16</b>Sat</div><div class="day"><b>17</b>Sun</div></div><div class="level-card" style="margin-top:23px"><small>LEVEL 3</small><h3>Consistent Learner</h3><p>1,240 XP · 760 XP to your next level</p><div class="mini-progress"><i style="--progress:62%"></i></div></div></article></section>
  <section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Your performance journey</h2><p>Recent assessment average compared with your target</p></div><button class="link-button" data-page="performance">Explore →</button></div>${chart('student')}<div class="chart-legend"><span>Your score</span><span>Target score</span></div></article><article class="card"><div class="card-heading"><div><h2>Today’s missions</h2><p>2 of 4 complete · +40 XP available</p></div></div><div class="plan-item"><span class="plan-check">✓</span><span><strong>Attend scheduled classes</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check">✓</span><span><strong>Review yesterday’s mistakes</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Mathematics practice</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>30-minute Programming session</strong><span>+10 XP</span></span></div></article></section>
</div>`;
}

function attendancePage() { return `<div class="page">${header('My Attendance', 'Your attendance helps you stay connected to learning.', false)}<section class="stat-grid">${stat('Attendance rate', '80%', '94 of 117 scheduled days', '#ddf5ee')}${stat('Days present', '94', 'May–August 2026', '#e8efff', 'gray')}${stat('Days absent', '23', 'Across four months', '#fff2d9', 'gray')}${stat('Holidays / no class', '6', 'Excluded from attendance rate', '#ddf5ee')}</section>${attendanceHeatmap()}<section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Attendance journey</h2><p>You’re meeting your 80% target across the four-month period. Keep your steady rhythm going.</p></div></div>${chart('student')}</article><article class="card"><div class="card-heading"><div><h2>Subjects where you can improve</h2><p>Supportive next steps—not a judgment.</p></div></div><div class="signal-list"><div class="signal"><span class="signal-icon">∑</span><span class="signal-name">Mathematics<small>Target: 80%</small></span><b class="signal-val">74%</b></div><div class="signal"><span class="signal-icon" style="--tint:#fff3e0;--colour:#b76c00">⌘</span><span class="signal-name">Programming<small>Target: 80%</small></span><b class="signal-val">74%</b></div><div class="signal"><span class="signal-icon" style="--tint:#e4f5ef;--colour:#187564">ϟ</span><span class="signal-name">Physics<small>On target</small></span><b style="color:#187564">89%</b></div></div></article></section></div>`; }
function performancePage() { return `<div class="page">${header('My Academic Performance', 'Use your trend to make smart, practical choices.', false)}<section class="stat-grid">${stat('Current average', '72%', '↑ 5% from last assessment', '#ddf5ee')}${stat('Previous average', '67%', '4 assessments ago', '#e8efff', 'gray')}${stat('Personal target', '80%', 'A steady, achievable goal', '#fff2d9', 'gray')}${stat('Programming progress', '+9%', 'Great recent improvement', '#ddf5ee')}</section><section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Your performance journey</h2><p>Scores across recent assessments · All subjects</p></div><select aria-label="Filter performance"><option>All subjects</option><option>Mathematics</option><option>Programming</option><option>Physics</option></select></div>${chart('student')}</article><article class="card"><div class="card-heading"><div><h2>Subject snapshot</h2><p>See what to maintain and where to focus</p></div></div><div class="signal-list"><div class="signal"><span class="signal-icon">∑</span><span class="signal-name">Mathematics<small>Previous 58% · Target 80%</small></span><b class="signal-val">64%</b></div><div class="signal"><span class="signal-icon" style="--tint:#eaf2ff;--colour:#3e69d6">⌘</span><span class="signal-name">Programming<small>Previous 69% · Target 80%</small></span><b style="color:#187564">78% ↑</b></div><div class="signal"><span class="signal-icon" style="--tint:#e4f5ef;--colour:#187564">ϟ</span><span class="signal-name">Physics<small>Previous 73% · Target 80%</small></span><b style="color:#187564">76%</b></div></div></article></section></div>`; }
function helperPage() { return `<div class="page">${header('Your Personal AI Study Helper', 'Your study plan adapts to the learning information available to SAGE.', false)}<section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Today’s recommendation</h2><p>Generated from your recent scores, study activity, and goals.</p></div><span class="pill green">Personalised</span></div><div class="insight-callout"><strong>Start with Mathematics today</strong><p>Your recent Mathematics score is below your 80% target, while Programming is improving. A short focused session can help you build confidence and momentum.</p></div><div class="plan-item" style="margin-top:10px"><span class="plan-check todo">1</span><span><strong>Mathematics fundamentals</strong><span>Review algebra concepts, then solve ten practice questions.</span></span><span class="plan-duration">45 min</span></div><div class="plan-item"><span class="plan-check todo">2</span><span><strong>Programming revision</strong><span>Continue your current practice routine.</span></span><span class="plan-duration">30 min</span></div><div class="plan-item"><span class="plan-check todo">3</span><span><strong>Quick reflection</strong><span>Note one question you want to ask in class.</span></span><span class="plan-duration">10 min</span></div><button class="primary wide" data-action="focus">Start study session</button></article><article class="card chat"><div class="card-heading"><div><h2>Ask SAGE</h2><p>Guidance based only on your available data</p></div></div><div class="chat-messages" id="chat-messages"><div class="chat-message"><strong>SAGE study helper</strong>Hi Aarav! I can help you plan a focused, realistic study session. What would you like to work on?</div><div class="chat-message you"><strong>You</strong>What should I focus on?</div><div class="chat-message"><strong>SAGE study helper</strong>Mathematics is a helpful focus this week: your recent score is below target and the last trend is improving slowly. Try 40 minutes of revision, ten practice questions, then 20 minutes of Programming to maintain your progress.</div></div><form class="chat-input" id="chat-form"><input aria-label="Ask the study helper" placeholder="Ask about your study plan..." /><button class="primary">Send</button></form></article></section><p style="color:#77859a;font-size:11px">SAGE recommendations are support suggestions, not academic decisions. They are generated from available demo learning data and should be used alongside teacher guidance.</p></div>`; }
function planPage() { return `<div class="page">${header('My Study Plan', 'A balanced plan shaped around your current goals and improvement areas.', false)}<section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Today · Thursday</h2><p>Keep it focused and achievable.</p></div><span class="pill green">105 mins</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Mathematics · Algebra revision</strong><span>Core concepts and 10 practice questions</span></span><span class="plan-duration">45 min</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Programming · Arrays practice</strong><span>Maintain your good momentum</span></span><span class="plan-duration">30 min</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Physics · Formula recall</strong><span>Short pre-class revision</span></span><span class="plan-duration">20 min</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Reflection</strong><span>Capture what felt difficult</span></span><span class="plan-duration">10 min</span></div></article><article class="card"><div class="card-heading"><div><h2>Weekly challenge</h2><p>Study for 25 minutes on 5 days.</p></div></div><div class="level-card"><small>+100 XP</small><h3>Build your momentum</h3><p>3 of 5 focused sessions completed this week.</p><div class="mini-progress"><i style="--progress:60%"></i></div></div><button class="secondary wide" data-action="focus">Start a focus session</button></article></section></div>`; }
function goalsPage() { return `<div class="page">${header('Goals & Missions', 'Positive learning activity builds confidence over time.', false)}<section class="content-grid"><article class="card"><div class="card-heading"><div><h2>Today’s missions</h2><p>2 complete · +20 XP earned</p></div></div><div class="plan-item"><span class="plan-check">✓</span><span><strong>Attend scheduled classes</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check">✓</span><span><strong>Review yesterday’s mistakes</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Mathematics practice</strong><span>+10 XP</span></span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Programming focus session</strong><span>+10 XP</span></span></div></article><article class="card"><div class="card-heading"><div><h2>Personal challenge</h2><p>Designed around your learning activity</p></div></div><div class="insight-callout"><strong>Complete three focused Mathematics sessions</strong><p>That’s a helpful way to give your current improvement area consistent attention. You decide the pace.</p></div><button class="primary wide" data-action="focus">Begin a session</button></article></section></div>`; }
function achievementsPage() { return `<div class="page">${header('My Achievements', 'Your XP represents positive learning activity—not intelligence.', false)}<section class="content-grid"><article class="level-card"><small>LEVEL 3</small><h3>Consistent Learner</h3><p>1,240 XP earned · 760 XP to Level 4: Focused Learner</p><div class="mini-progress"><i style="--progress:62%"></i></div></article><article class="card"><div class="card-heading"><div><h2>Learning streak</h2><p>7 days of showing up for yourself.</p></div><strong style="color:#e38d11">7 🔥</strong></div><div class="streak"><div class="day done"><b>✓</b>Mon</div><div class="day done"><b>✓</b>Tue</div><div class="day done"><b>✓</b>Wed</div><div class="day today"><b>14</b>Thu</div><div class="day"><b>15</b>Fri</div><div class="day"><b>16</b>Sat</div><div class="day"><b>17</b>Sun</div></div></article></section><section class="card"><div class="card-heading"><div><h2>Badge collection</h2><p>Celebrate the habits you’re building.</p></div></div><div class="badge-grid"><div class="badge"><div class="badge-icon">✦</div><strong>First Step</strong></div><div class="badge"><div class="badge-icon">🔥</div><strong>7-Day Learner</strong></div><div class="badge"><div class="badge-icon">↗</div><strong>Early Improver</strong></div><div class="badge"><div class="badge-icon">✓</div><strong>Consistency Champion</strong></div><div class="badge locked"><div class="badge-icon">★</div><strong>Subject Master</strong></div><div class="badge locked"><div class="badge-icon">♜</div><strong>Attendance Hero</strong></div></div></section></div>`; }
function studentInterventions() { return `<div class="page">${header('My Support Plan', 'Additional support is here to help you move forward.', false)}<section class="content-grid"><article class="card"><div class="card-heading"><div><h2>You have a new support plan</h2><p>Assigned by Prof. Kiran Rao · Reviewed together</p></div><span class="pill blue">Active</span></div><div class="insight-callout"><strong>Academic mentoring</strong><p>We noticed a few areas where extra support may help. This plan focuses on Mathematics practice and a regular mentor check-in.</p></div><div class="plan-item" style="margin-top:10px"><span class="plan-check">✓</span><span><strong>Meet your mentor</strong><span>Friday, 3:30 PM</span></span><span class="plan-duration">Upcoming</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Complete practice set</strong><span>Ten Mathematics questions</span></span><span class="plan-duration">This week</span></div><div class="plan-item"><span class="plan-check todo">○</span><span><strong>Attend revision session</strong><span>Tuesday · Room B-204</span></span><span class="plan-duration">Tue</span></div></article><article class="card"><div class="card-heading"><div><h2>Progress after support</h2><p>Demo / simulated progress</p></div></div><div class="change"><strong>Mathematics</strong><span>52% → 68%</span><small style="color:#187564">↑ 16 percentage points</small></div><div class="insight-callout" style="margin-top:13px"><strong>Great progress—keep your routine.</strong><p>Continue using your weekly plan and bring any difficult topics to your mentor.</p></div></article></section></div>`; }
function studentFeedback() { return `<div class="page">${header('Student Feedback', 'Help improve the learning environment for everyone.', false)}<section class="content-grid"><article class="card feedback-form"><div class="card-heading"><div><h2>Share your experience</h2><p>Your feedback helps the college understand recurring issues. You can submit anonymously.</p></div></div><div class="field"><span>What would you like to share?</span><div class="category-buttons">${['Internet / Wi-Fi', 'Classroom', 'Library', 'Teaching support', 'Canteen', 'Campus environment'].map(c => `<button type="button" class="category-button ${state.selectedCategory === c ? 'active' : ''}" data-category="${c}">${c}</button>`).join('')}</div></div><div class="field"><span>How would you rate it?</span><div class="rating" role="group" aria-label="Choose a rating from 1 to 5">${[1, 2, 3, 4, 5].map(n => `<button type="button" class="${n <= state.rating ? 'selected' : ''}" data-rating="${n}" aria-label="${n} stars">★</button>`).join('')}</div></div><label class="field">Your feedback<textarea id="feedback-text" placeholder="Tell us what is working or what could be improved..."></textarea></label><label class="check-row"><input id="anonymous" type="checkbox" checked /> Submit anonymously</label><button class="primary wide" data-action="submit-feedback">Submit feedback</button></article><article class="card"><div class="card-heading"><div><h2>Your privacy matters</h2><p>How SAGE handles feedback</p></div></div><div class="signal-list"><div class="signal"><span class="signal-icon">◌</span><span class="signal-name">Anonymous by choice<small>Staff insights are aggregated by default.</small></span></div><div class="signal"><span class="signal-icon" style="--tint:#e4f5ef;--colour:#187564">✓</span><span class="signal-name">Action-focused<small>Feedback is grouped into recurring themes.</small></span></div><div class="signal"><span class="signal-icon" style="--tint:#eaf2ff;--colour:#3e69d6">⌁</span><span class="signal-name">No automatic judgments<small>Feedback is never used for disciplinary decisions.</small></span></div></div><div class="explanation" style="margin-top:16px">Your feedback joins an aggregate view that helps staff identify potential institutional support barriers.</div></article></section></div>`; }
function notificationsPage() { return `<div class="page">${header('Notifications', 'Helpful reminders and positive updates.', false)}<section class="card"><div class="plan-item"><span class="plan-check">✦</span><span><strong>You earned the 7-Day Learner badge!</strong><span>Keep building a study habit that works for you.</span></span><span class="plan-duration">Today</span></div><div class="plan-item"><span class="plan-check">◷</span><span><strong>Mathematics study goal is due today</strong><span>A 45-minute focus session is ready when you are.</span></span><span class="plan-duration">Today</span></div><div class="plan-item"><span class="plan-check">◌</span><span><strong>Your mentor scheduled a check-in</strong><span>Friday at 3:30 PM · Academic mentoring</span></span><span class="plan-duration">Yesterday</span></div></section></div>`; }
function profilePage() { return `<div class="page">${header('My Profile', 'The information you choose to share with your learning support team.', false)}<section class="content-grid"><article class="card profile-card"><span class="avatar mint" style="width:68px;height:68px;font-size:20px">AS</span><span><h2>Aarav Sharma</h2><p>STU-2026-0147 · B.Tech Computer Science · Semester 3</p><p style="margin-top:7px">Level 3 · 1,240 XP · 7-day streak</p></span></article><article class="card"><div class="card-heading"><div><h2>Study preferences</h2><p>Used to make your plan more useful.</p></div></div><p style="color:#536278;font-size:12px;line-height:1.7">Preferred focus time: 6:00–7:30 PM<br>Goal style: Short daily sessions<br>Reminder preference: Evening notification</p><button class="secondary" data-action="note">Update preferences</button></article></section></div>`; }

function genericPage() { const title = pageName(); return `<div class="page">${header(title, 'A prototype view within the SAGE student-support platform.')}<section class="card"><div class="card-heading"><div><h2>${title}</h2><p>This view is ready to be connected to your real institutional data and workflow.</p></div></div><div class="insight-callout"><strong>Prototype-ready foundation</strong><p>SAGE uses synthetic data in this demo. Any real deployment must include local validation, role-based access, human review, and appropriate privacy safeguards.</p></div></section></div>`; }

function renderPage() {
  const content = document.querySelector('#page-content');
  if (!content) return;
  let template;
  if (state.role === 'admin') template = state.page === 'dashboard' ? adminDashboard() : state.page === 'feedback' ? feedbackDashboard() : state.page === 'students' ? profileDetail() : genericPage();
  else if (state.role === 'faculty') template = state.page === 'dashboard' ? facultyDashboard() : state.page === 'students' ? profileDetail() : genericPage();
  else {
    const pages = { dashboard: studentDashboard, attendance: attendancePage, performance: performancePage, helper: helperPage, plan: planPage, goals: goalsPage, achievements: achievementsPage, interventions: studentInterventions, feedback: studentFeedback, notifications: notificationsPage, profile: profilePage };
    template = (pages[state.page] || genericPage)();
  }
  content.innerHTML = template;
  document.querySelector('.sidebar')?.classList.remove('open');
  content.querySelectorAll('[data-page]').forEach(btn => btn.addEventListener('click', () => { state.page = btn.dataset.page; renderPage(); }));
  content.querySelectorAll('[data-action]').forEach(btn => btn.addEventListener('click', actionHandler));
  content.querySelectorAll('[data-category]').forEach(btn => btn.addEventListener('click', () => { state.selectedCategory = btn.dataset.category; renderPage(); }));
  content.querySelectorAll('[data-rating]').forEach(btn => btn.addEventListener('click', () => { state.rating = Number(btn.dataset.rating); renderPage(); }));
  content.querySelector('#chat-form')?.addEventListener('submit', sendChat);
}

function actionHandler(event) {
  const action = event.currentTarget.dataset.action;
  if (action === 'theme') { toggleTheme(); return; }
  if (action === 'logout') { clearInterval(state.timer); state.page = 'dashboard'; showWelcome(); return; }
  if (action === 'student-detail') { state.page = 'students'; if (state.role === 'admin') state.page = 'students'; renderPage(); return; }
  if (action === 'intervention') { showModal('Review support plan', `<p>Assigning a plan always needs human approval. In this demo, the plan contains mentoring, guided practice, and a follow-up check-in.</p><label class="field">Faculty note<textarea placeholder="Add a supportive note for the student"></textarea></label><button class="primary wide" id="confirm-intervention">Assign support plan</button>`); document.querySelector('#confirm-intervention').addEventListener('click', () => { closeModal(); toast('Support plan assigned. Aarav will see a supportive next-step view.'); }); return; }
  if (action === 'issue-modal') { showModal('Wi-Fi connectivity', `<p><b>43 simulated feedback mentions</b> · Average rating: <b>2.1 / 5</b> · Trend: <b>Increasing</b></p><div class="explanation" style="margin-top:15px">“Wi-Fi doesn’t reach the second floor.”<br><br>“Library connection keeps dropping.”<br><br>“Internet is too slow during study time.”</div><label class="field">Update issue status<select id="issue-status"><option>Under review</option><option>Action planned</option><option>In progress</option><option>Resolved</option></select></label><label class="field">Staff note<textarea placeholder="e.g. IT department notified. Access point planned."></textarea></label><button class="primary wide" id="save-issue">Save update</button>`); document.querySelector('#save-issue').addEventListener('click', () => { closeModal(); toast('Issue action updated. Student feedback remains protected in aggregate reporting.'); }); return; }
  if (action === 'submit-feedback') { const feedback = document.querySelector('#feedback-text')?.value.trim(); if (!state.rating) { toast('Choose a star rating before submitting.'); return; } if (!feedback) { toast('Add a short comment so staff can understand the issue.'); return; } showModal('Feedback submitted', `<p>Thank you for helping improve the student experience. Your feedback is now part of the aggregated <b>${state.selectedCategory}</b> insight.</p><div class="insight-callout" style="margin-top:15px"><strong>${document.querySelector('#anonymous')?.checked ? 'Submitted anonymously' : 'Submitted with your identity'}</strong><p>Staff normally view aggregate feedback patterns. No automatic action is taken from a single submission.</p></div><button class="primary wide" id="done-feedback">Done</button>`); document.querySelector('#done-feedback').addEventListener('click', () => { closeModal(); state.rating = 0; toast('Your feedback was recorded. Thank you.'); renderPage(); }); return; }
  if (action === 'focus') { showFocusModal(); return; }
  if (action === 'help') { showModal('Need support?', `<p>SAGE can help you reach the right person. This demo does not provide emergency services or mental-health diagnosis.</p><div class="plan-item"><span class="plan-check">◌</span><span><strong>Talk to a mentor</strong><span>Academic planning and study support</span></span></div><div class="plan-item"><span class="plan-check">◌</span><span><strong>Request academic help</strong><span>Subject-specific support</span></span></div><div class="plan-item"><span class="plan-check">◌</span><span><strong>Request counselor support</strong><span>Connect with your college support service</span></span></div><button class="primary wide" id="help-request">Send support request</button>`); document.querySelector('#help-request').addEventListener('click', () => { closeModal(); toast('Support request prepared for the appropriate team.'); }); return; }
  if (action === 'notifications') { state.role === 'student' ? (state.page = 'notifications', renderPage()) : toast('No new notifications.'); return; }
  if (action === 'note') { toast('This prototype action is ready for your backend integration.'); }
}

function showModal(title, body) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="modal-backdrop" role="dialog" aria-modal="true" aria-label="${title}"><section class="modal"><div class="modal-top"><div><h2>${title}</h2><p>Demo prototype</p></div><button class="icon-button" id="modal-close" aria-label="Close">×</button></div>${body}</section></div>`); document.querySelector('#modal-close').addEventListener('click', closeModal); document.querySelector('#modal-backdrop').addEventListener('click', e => { if (e.target.id === 'modal-backdrop') closeModal(); }); }
function closeModal() { clearInterval(state.timer); state.timer = null; document.querySelector('#modal-backdrop')?.remove(); }
function showFocusModal() { state.seconds = 25 * 60; showModal('Focus session', `<p>Choose one task, remove distractions, and give it your full attention.</p><div style="text-align:center;padding:20px 0"><div id="timer" style="font:800 54px 'Plus Jakarta Sans';letter-spacing:-.08em;color:#146c62">25:00</div><div style="color:#718096;font-size:12px;margin-top:7px">Mathematics · Algebra revision</div></div><button class="primary wide" id="timer-start">Start focus timer</button><button class="secondary wide" style="margin-top:9px" id="timer-complete">Complete session</button>`); document.querySelector('#timer-start').addEventListener('click', startTimer); document.querySelector('#timer-complete').addEventListener('click', () => { closeModal(); toast('Session completed! You earned +20 XP for focused learning.'); }); }
function startTimer() { const button = document.querySelector('#timer-start'); if (state.timer) { clearInterval(state.timer); state.timer = null; button.textContent = 'Resume focus timer'; return; } button.textContent = 'Pause timer'; state.timer = setInterval(() => { state.seconds--; const mins = Math.floor(state.seconds / 60); const secs = state.seconds % 60; const timer = document.querySelector('#timer'); if (timer) timer.textContent = `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`; if (state.seconds <= 0) { clearInterval(state.timer); state.timer = null; closeModal(); toast('Session completed! You earned +20 XP.'); } }, 1000); }
function sendChat(e) { e.preventDefault(); const input = e.currentTarget.querySelector('input'); const text = input.value.trim(); if (!text) return; const messages = document.querySelector('#chat-messages'); messages.insertAdjacentHTML('beforeend', `<div class="chat-message you"><strong>You</strong>${escapeHtml(text)}</div>`); input.value = ''; setTimeout(() => { messages.insertAdjacentHTML('beforeend', `<div class="chat-message"><strong>SAGE study helper</strong>Based on the available progress data, keep your next step small and specific: revise one Mathematics concept, try a few questions, and note what you want to clarify with your teacher. You’re building momentum.</div>`); messages.scrollTop = messages.scrollHeight; }, 350); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function toast(message) { const region = document.querySelector('#toast-region'); const id = `toast-${Date.now()}`; region.insertAdjacentHTML('beforeend', `<div class="toast" id="${id}"><strong>✓</strong>${message}</div>`); setTimeout(() => document.querySelector(`#${id}`)?.remove(), 4200); }
function applyTheme() { document.documentElement.dataset.theme = state.theme; }
function toggleTheme() {
  state.theme = state.theme === 'light' ? 'dark' : 'light';
  try { localStorage.setItem('sage-theme', state.theme); } catch { /* Theme remains available for this session. */ }
  applyTheme();
  if (document.querySelector('.shell')) shell(); else showWelcome();
}

applyTheme();
showWelcome();
